version: '3.3'
services:
  db:
    container_name: servidor-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sa_db
    ports:
        - "3307:3306"          
    volumes:
        - "./servidordb1/initscript.sql:/docker-entrypoint-initdb.d/1.sql"   
        - ./servidordb1/mysql/data:/var/lib/mysql      
  web:
    container_name: servidor-web
    build: ./servidor-web
    image: servidor-web-practica8
    ports:
      - "8080:5000"  
  db2:
    container_name: servidor-db2
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sa_db
    ports:
        - "3308:3306"          
    volumes:
        - "./servidordb2/initscript.sql:/docker-entrypoint-initdb.d/1.sql"   
        - ./servidordb2/mysql/data:/var/lib/mysql      
